name: p3p
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  dart_pg: ^1.1.5
  dio: ^5.3.2
  drift: ^2.11.0
  isar: ^3.1.0+1
  logger: ^2.0.2
  mutex: ^3.0.1
  path: ^1.8.3
  rxdart: ^0.27.7
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.0
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
