name: p3p
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://git.mrcyjanek.net/p3pch4t/p3p.dart
publish_to: https://git.mrcyjanek.net/api/packages/p3pch4t/pub

environment:
  sdk: ^3.0.0

dev_dependencies:
  build_runner: 2.4.8
  ffigen: 9.0.1
  lints: 3.0.0
  test: 1.25.1
  very_good_analysis: 5.1.0

ffigen:
  name: 'P3pgo'
  description: 'Bindings to p3p golang api'
  
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'vendor/api_host.h'

dependencies:
  ffi: ^2.1.0
